### ISSUE TITLE
Should `descriptor_pool_info` include `FREE_DESCRIPTOR_SET` flag?

### ISSUE THREAD

**Issue by dannycoates** [kvark/blade#117] opened 2024-05-14 13:35 UTC
From https://github.com/zed-industries/zed/issues/10018#issuecomment-2107354282

**Comment by progmboy** [comment] 2024-05-27 11:50
After several hours of debugging, I can confirm that this issue only occurs with Intel's drivers.

```
filename: igvk64.dll
fileversion: 31.0.101.4502
filedescription: Vulkan(R) Driver for Intel(R) Graphics Accelerator
```

```c
__int64 __fastcall vkDescriptorAllocatePoolSet(__int64 a1, __int64 a2, __int64 a3)
{
	...
	// Check descriptor_pool->dword424 is bigger than set.
	// the throw VK_ERROR_OUT_OF_POOL_MEMORY error.
	//
	// When this error occurs.
	// 0:000> dd 0x00000212bdec4878+424 l1
	// 00000212`bdec4c9c  0000ea60
	// 0:000> dd 0x00000212bdec4878+420 l1
	// 00000212`bdec4c98  0000ea60
	//
	if ( v11 && (unsigned int)(descriptor_pool->dword424 + 1) > descriptor_pool->dword420 )
        {
            sub_180470550(&v36, 20LL);
            v37[0] = v36;
            CxxThrowException(v37, (_ThrowInfo *)&_TI1_AUException_VK__);
        }
	...

	// here inc dword424 
        *(_DWORD *)(v14 + 68) = descriptor_pool->dword424++;
        v30 = v12;
        v20 = v11;
        v21 = playout;
}
```

```c
__int64 __fastcall vkResetDescriptorPool(__int64 hDevice, struct_descriptor_pool *descriptor_pool)
{
	// 
	// VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT = 1
	// defalut descriptor_pool->flags == 0
	// 
	if ( descriptor_pool->flags ){
		...
	
		//
		//  void __fastcall sub_18039C3B0(struct_descriptor_pool *descriptor_pool, __int64 a2)
		//  {
		//	 ...
		//	 // ONLY this way to dec descriptor_pool->dword424
		//   descriptor_pool->dword424 -= *(_DWORD *)(a2 + 68) != -1;
  		//   v16 = *(unsigned int *)(a2 + 68);
		//   ...
		// 	}
		//
	
		sub_18039C3B0(descriptor_pool, v11);
		...
	}else{
		// NERVER DEC descriptor_pool->dword424 
	}
}
```

**Comment by kvark** [comment] 2024-05-28 00:08
nice work, @progmboy ! Would you be able to file this upstream to Intel folks? Seems rather serious.

**Comment by skejeton** [comment] 2024-06-08 11:35
@kvark Does adding `FREE_DESCRIPTOR_SET` flag affect other platforms? From Vulkan specification:
> VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT specifies that descriptor sets can return their individual allocations to the pool, i.e. all of [vkAllocateDescriptorSets](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkAllocateDescriptorSets.html), [vkFreeDescriptorSets](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkFreeDescriptorSets.html), and [vkResetDescriptorPool](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkResetDescriptorPool.html) are allowed. Otherwise, descriptor sets allocated from the pool must not be individually freed back to the pool, i.e. only [vkAllocateDescriptorSets](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkAllocateDescriptorSets.html) and [vkResetDescriptorPool](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkResetDescriptorPool.html) are allowed.

Even though blade only releases entire pools, it seems like this flag only extends you to allow to release each set individually. If this fixes the Intel driver bug, and doesn't meddle with other graphics card, I think it'd be a good solution.

**Comment by kvark** [comment] 2024-06-09 07:15
I suspect it may change the allocation strategy for the descriptors, thus making it slower for us to allocate new ones. And this would be potentially significant since Blade relies on allocating descriptors many times per frame, potentially thousands of times.
For this reason, and the fact that the current code agrees with Vulkan spec, I wouldn't want to put this workaround unconditionally. I am, however, open to put it explicitly as a workaround for a specific platform bug.
Looks to be affecting Windows Intel 11th gen? That's a pretty popular config...

**Comment by skejeton** [comment] 2024-06-09 11:58
Yeah sounds good.

**Comment by skejeton** [comment] 2024-06-09 11:59
Interestingly, someone else is having this issue but on an AMD GPU: https://github.com/zed-industries/zed/issues/12561#issuecomment-2156365422
I'm not sure if these are related.

**Comment by shenjackyuanjie** [comment] 2024-06-09 15:28
![image](https://github.com/kvark/blade/assets/54507071/783ca2e2-51f5-4b7b-8a6f-f10503e59ef3)

more about the GPU
it's an RX 580 8G
with the latest driver of 24.3.1

![image](https://github.com/kvark/blade/assets/54507071/542ed427-da7c-4109-87a8-9c168313ca2f)

**Comment by kvark** [comment] 2024-06-10 04:56
Uhh, that's rather unfortunate. Maybe it's just a Windows thing in general?

**Comment by shenjackyuanjie** [comment] 2024-06-10 04:57
> Uhh, that's rather unfortunate. Maybe it's just a Windows thing in general?

but there is some good news, on zed's last commit, it looks fine

e829a8c3b0564bc902cc0d0a530099be7f0f036e

**Comment by kvark** [comment] 2024-06-10 05:15
ah, ok, phew, so it was addressed by https://github.com/kvark/blade/pull/118

**Comment by kvark** [comment] 2024-07-09 15:37
Closed by #129

**Closed by kvark** 2024-07-09 15:37 UTC

**Comment by progmboy** [comment] 2025-03-18 12:04
> I suspect it may change the allocation strategy for the descriptors, thus making it slower for us to allocate new ones. And this would be potentially significant since Blade relies on allocating descriptors many times per frame, potentially thousands of times. For this reason, and the fact that the current code agrees with Vulkan spec, I wouldn't want to put this workaround unconditionally. I am, however, open to put it explicitly as a workaround for a specific platform bug. Looks to be affecting Windows Intel 11th gen? That's a pretty popular config...

UPDATE:

```
filename: igvk64.dll
fileversion: 32.0.101.5768
filedescription: Vulkan(R) Driver for Intel(R) Graphics Accelerator
```

I tested again with the new version of igvk64.dll(32.0.101.5768) and disabled patch #118 . It seems that Intel has fixed this, the VK_ERROR_OUT_OF_POOL_MEMORY never occurs. @ske2004 @kvark could you please confirm this as well? If it is confirmed to be fixed, should we consider disabling this patch?

**Comment by progmboy** [comment] 2025-03-18 12:36
> > I suspect it may change the allocation strategy for the descriptors, thus making it slower for us to allocate new ones. And this would be potentially significant since Blade relies on allocating descriptors many times per frame, potentially thousands of times. For this reason, and the fact that the current code agrees with Vulkan spec, I wouldn't want to put this workaround unconditionally. I am, however, open to put it explicitly as a workaround for a specific platform bug. Looks to be affecting Windows Intel 11th gen? That's a pretty popular config...
> 
> UPDATE:
> 
> ```
> filename: igvk64.dll
> fileversion: 32.0.101.5768
> filedescription: Vulkan(R) Driver for Intel(R) Graphics Accelerator
> ```
> 
> I tested again with the new version of igvk64.dll(32.0.101.5768) and disabled patch [#129](https://github.com/kvark/blade/pull/129) . It seems that Intel has fixed this, the VK_ERROR_OUT_OF_POOL_MEMORY never occurs. [@ske2004](https://github.com/ske2004) [@kvark](https://github.com/kvark) could you please confirm this as well? If it is confirmed to be fixed, should we consider disabling this patch?

VK_ERROR_OUT_OF_POOL_MEMORY disappear。But I find other panic `panic_const_mul_overflow`  T_T

```
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/43a2e9d2c72db101f5fedac8b3acb78981b06bf2/library\std\src\panicking.rs:695
   1: core::panicking::panic_fmt
             at /rustc/43a2e9d2c72db101f5fedac8b3acb78981b06bf2/library\core\src\panicking.rs:75
   2: core::panicking::panic_const::panic_const_mul_overflow
             at /rustc/43a2e9d2c72db101f5fedac8b3acb78981b06bf2/library\core\src\panicking.rs:178
   3: blade_graphics::hal::Device::create_descriptor_sub_pool
             at C:\Users\pgboy\.cargo\git\checkouts\blade-26bd638d88226de3\b16f5c7\blade-graphics\src\vulkan\descriptor.rs:19
   4: blade_graphics::hal::Device::allocate_descriptor_set
             at C:\Users\pgboy\.cargo\git\checkouts\blade-26bd638d88226de3\b16f5c7\blade-graphics\src\vulkan\descriptor.rs:97
   5: blade_graphics::hal::command::impl$27::bind<gpui::platform::blade::blade_renderer::ShaderMonoSpritesData>
             at C:\Users\pgboy\.cargo\git\checkouts\blade-26bd638d88226de3\b16f5c7\blade-graphics\src\vulkan\command.rs:908
```
